package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"backend/graph/generated"
	"backend/graph/model"
	"backend/internal/address"
	"context"
)

// AddressGet is the resolver for the addressGet field.
func (r *queryResolver) AddressGet(ctx context.Context, id *string) ([]*model.Address, error) {
	var ret []*model.Address
	var address address.Address
	res, err := address.Get(id)
	if err != nil {
		return ret, err
	}
	ret = append(ret, res)
	return ret, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
