package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"backend/graph/model"
	"context"
	"fmt"
)

// CityGet is the resolver for the cityGet field.
func (r *queryResolver) CityGet(ctx context.Context, id *string) ([]*model.City, error) {
	panic(fmt.Errorf("not implemented: CityGet - cityGet"))
}
