package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"backend/graph/model"
	"context"
	"fmt"
)

// DistrictGet is the resolver for the districtGet field.
func (r *queryResolver) DistrictGet(ctx context.Context, id *string) ([]*model.District, error) {
	panic(fmt.Errorf("not implemented: DistrictGet - districtGet"))
}
