package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"backend/graph/generated"
	"backend/graph/model"
	"backend/internal/user"
	"context"
)

// UserCreate is the resolver for the userCreate field.
func (r *mutationResolver) UserCreate(ctx context.Context, data model.UserInput) (*model.User, error) {
	// var ret []*model.User
	var user user.User
	return user.Create(data)
}

// UserGet is the resolver for the userGet field.
func (r *queryResolver) UserGet(ctx context.Context, id *string) ([]*model.User, error) {
	var ret []*model.User
	var user user.User
	res, err := user.Get(id)
	if err != nil {
		return ret, err
	}
	ret = append(ret, res)
	return ret, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
