// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	Phone string `json:"phone"`
	Otp   string `json:"otp"`
}

type UserInput struct {
	ID     string `json:"id"`
	Email  string `json:"email"`
	Phone  string `json:"phone"`
	Otp    string `json:"otp"`
	Source string `json:"source"`
}
